// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUbXOl6IsDm3wEqRanzCjWSkjnjOjzmlk',
    appId: '1:330923245528:web:264962af4fd51dacd93cad',
    messagingSenderId: '330923245528',
    projectId: 'voish-e0361',
    authDomain: 'voish-e0361.firebaseapp.com',
    storageBucket: 'voish-e0361.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUbXOl6IsDm3wEqRanzCjWSkjnjOjzmlk',
    appId:
        '1:330923245528:android:placeholder', // AppID is platform specific, kept placeholder
    messagingSenderId: '330923245528',
    projectId: 'voish-e0361',
    storageBucket: 'voish-e0361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSy-PLACEHOLDER-KEY-PLEASE-UPDATE',
    appId: '1:123456789:ios:placeholder',
    messagingSenderId: '123456789',
    projectId: 'placeholder-project',
    storageBucket: 'placeholder-project.appspot.com',
    iosBundleId: 'com.example.voish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSy-PLACEHOLDER-KEY-PLEASE-UPDATE',
    appId: '1:123456789:ios:placeholder',
    messagingSenderId: '123456789',
    projectId: 'placeholder-project',
    storageBucket: 'placeholder-project.appspot.com',
    iosBundleId: 'com.example.voish',
  );
}
